/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f8efea",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface": "#1e1b18",
        "surface-tint": "#954824",
        "primary-container": "#d67b52",
        "surface-container-high": "#efe6e2",
        primary: "#954824",
        "surface-container": "#f5ece7",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb596",
        "error-container": "#ffdad6",
        tertiary: "#645d53",
        "surface-variant": "#e9e1dc",
        "surface-container-low": "#fbf2ed",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#77320e",
        "secondary-container": "#cee5da",
        "secondary-fixed": "#d1e8dd",
        error: "#ba1a1a",
        secondary: "#4e635a",
        "on-background": "#1e1b18",
        "outline-variant": "#dac1b8",
        "tertiary-container": "#9a9286",
        "on-tertiary-container": "#302b23",
        background: "#fff8f5",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdbcd",
        "secondary-fixed-dim": "#b5ccc1",
        "on-tertiary-fixed-variant": "#4c463c",
        outline: "#87736b",
        "tertiary-fixed-dim": "#cfc5b9",
        "on-secondary-fixed": "#0b1f18",
        "on-surface-variant": "#54433c",
        "tertiary-fixed": "#ebe1d4",
        "on-primary-fixed": "#360f00",
        "surface-bright": "#fff8f5",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb596",
        "on-tertiary-fixed": "#1f1b13",
        "on-primary-container": "#501a00",
        "on-secondary-fixed-variant": "#374b43",
        "surface-dim": "#e1d8d4",
        "inverse-surface": "#34302c",
        surface: "#fff8f5",
        "on-secondary-container": "#52675e",
        "surface-container-highest": "#e9e1dc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "stack-lg": "48px",
        "margin-mobile": "16px",
        "stack-sm": "12px",
        gutter: "24px",
        "stack-md": "24px",
        "container-max": "1280px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Playfair Display"],
        "label-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Playfair Display"],
      },
      fontSize: {
        "body-md": [
          "16px",
          {
            lineHeight: "24px",
            fontWeight: "400",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "32px",
            fontWeight: "600",
          },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.03em",
            fontWeight: "500",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "headline-lg-mobile": [
          "28px",
          {
            lineHeight: "36px",
            fontWeight: "600",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "28px",
            fontWeight: "400",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [],
};
